// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlYk8vF9hofS2Y0nf0slSNG3YTrAtcdlA',
    appId: '1:392216479237:web:48be8672a3a8727f4ebe6c',
    messagingSenderId: '392216479237',
    projectId: 'bustling-folio-409006',
    authDomain: 'bustling-folio-409006.firebaseapp.com',
    storageBucket: 'bustling-folio-409006.appspot.com',
    measurementId: 'G-BG1LDB10QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUsAWKWSUS1j5TBh2FYqfp50hLEBC_nME',
    appId: '1:392216479237:android:8f6ff59849e1c1724ebe6c',
    messagingSenderId: '392216479237',
    projectId: 'bustling-folio-409006',
    storageBucket: 'bustling-folio-409006.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9bcCERDvtEjzxDAvrpL-Oa_6pu-pVpDY',
    appId: '1:392216479237:ios:ab782c26d151d7b34ebe6c',
    messagingSenderId: '392216479237',
    projectId: 'bustling-folio-409006',
    storageBucket: 'bustling-folio-409006.appspot.com',
    iosBundleId: 'com.hariapp.educationalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9bcCERDvtEjzxDAvrpL-Oa_6pu-pVpDY',
    appId: '1:392216479237:ios:fa79adf758702f234ebe6c',
    messagingSenderId: '392216479237',
    projectId: 'bustling-folio-409006',
    storageBucket: 'bustling-folio-409006.appspot.com',
    iosBundleId: 'com.hariapp.educationalApp.RunnerTests',
  );
}
